### ISSUE TITLE
Menu 관련 TODO list

### ISSUE THREAD

**Issue by crontable** [sannimdev/cnkcoffee#5]
- [X] Connection 객체 수정
- [X] Connection 객체 닫기
- [ ] MenuDTO에 categoryName 항목 추가 (readMenu 등에서는 categoryName을 참조할 수 있도록 menu_category테이블과 조인 필요)
